---
- name: install ftp on machines running redhat AND version 7
  hosts: web
  tasks:
    - name: install ftp
      yum:
        name: ftp
        state: installed
      when: ansible_distribution == 'RedHat' or ansible_distribution_major_version == '7' 
