---
- name: Restart Services if a line echos
  hosts: web
  tasks:
    - name: Print this line
      command: echo "If this prints, then restart services"
      notify: "restart services"
  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
      listen: "restart services"
    - name: Restart Rsyslog
      service:
        name: rsyslog
        state: restarted
      listen: "restart services"
