---
- name: Ansible facts use case
  hosts: all
  tasks:
    - name: Capture the kernel information
      copy:
        content: "The available kernel version is {{ ansible_kernel }}"
        dest: /tmp/kernel_version.txt
...
