---
- name: Example of Conditional - installing httpd
  hosts: web
  tasks:
    - name: Install apache web server in RHEL based machine
      yum:
        name: httpd
        state: installed
      when: ansible_distribution == "RedHat"

    - name: Install apache web server in Ubuntu Based Machine
      apt:
        name: apache
        state: present
      when: ansible_distribution == "Ubuntu"
