---
- name: install and configure apache
  hosts: web
  tasks:
    - name: install Apache
      yum:
        name: httpd
        state: latest
    - name: start Apache
      service:
        name: httpd
        state: started
        enabled: true
    - name: Configure index.html
      copy:
        content: "Hassan Classes are awesome"
        dest: /var/www/html/index.html
    - name: restart Apache
      service:
        name: httpd
        state: restarted
    - name: configure firewall setting for Apache
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
      tags: fire_tag
    - name: Reload firewall
      service:
        name: firewalld
        state: restarted
      tags: fire_tag
