---
- name: instal and configure apache for nodes
  hosts: web
  tasks:
    - name: check if installed.
      yum:
        name: httpd
        state: latest
    - service:
        name: httpd
        state: started
        enabled: true
    - name: configure index.html
      template:
        src: ~/automation/templates/index.j2
        dest: /var/www/html/index.html
    - name: restart Apache
      service:
        name: httpd
        state: restarted
    - name: firewalld
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
