---
- name: Example of Mapping Variable
  hosts: web
  tasks:
    - name: Create new users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
      loop:
        - name: vikas
          uid: 1020
        - name: amit
          uid: 1021
        - name: greta
          uid: 1022
