---
- name: MOTD file creation playbook
  hosts: web
  tasks:
    - name: Copying MOTD file from Ansible server to managed nodes
      template:
        src: ~/automation/templates/motd.j2
        dest: /etc/motd
