---
- name: Create a file called packages.yml in /home/sandy/ansible to install some packages for the following hosts. On dev, prod and webservers install packages httpd, mod_ssl, and mariadb. On dev only install the development tools package. Also, on dev host update all the packages to the latest.
  hosts: t480,x230
  become: true
  tasks:
    - name: install 3 packages
      yum:
        name:
          - httpd
          - mod_ssl
          - mariadb
        state: present
    - name: install development package
      yum:
        name: '@Development tools'
        state: present
      when: "t480" in group_names
    - name: update all packages
      yum:
        name: '*'
        state: latest
      when: "x230" in group_names
