---
- name: practice of variable precedence
  hosts: node1
  become: yes
  vars:
    myvar: "This is a playbook variable"
    apache: httpd
    apache_root: /var/www/htmlvar
    packages:
      - ftp
      - vsftpd
      - zsh
  vars_files:
    - ~/automation/playbooks/practice_variables_file.yml
  vars_prompt:
    - name: user_name
      prompt: Please enter your username
    - name: pass_word
      prompt: Please enter your password
      private: yes
  tasks:
    - name: just a debug message to output variables.
      debug:
        msg: "{{ myvar }}"

    - name: install httpd service
      yum:
        name: "{{ apache }}"
        state: installed

    - name: create apache directory
      file:
        path: "{{ apache_root }}"
        state: directory
    - name: create index.html
      copy:
        content: "Welcome to nehra classes"
        dest: "{{ apache_root }}/index.html"

    - name: ARRAY & LIST type if [1] not specified
      yum:
        name: "{{ packages[1] }}"
        state: installed

    - name: MAPPING VARIABLES
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
      loop:
        - name: kuku
          uid: 1040
        - name: kokni
          uid: 1041
        - name: gogni
          uid: 1042

    - name: PROMPT
      debug:
        msg: "The username is {{ user_name }} and Password is {{ pass_word }}"

    - name: VARIABLES DEFINED IN INVENTORY FILE - but BETTER host_vars , group_vars
      file:
        path: "{{ dir }}"
        state: directory



    - name: REGISTERED VARIABLES
      command: hostname
      register: abc
    - name: PRINT
      debug:
        var: abc.stdout
    - name: COPY
      copy:
        content: This is the server hostname "{{ abc.stdout }}"
        dest: /tmp/variable1

    - name: REGISTERED VARIABLES 1 - PRINT RESULTING VALUES
      file: 
        path: /home/rupert/variables2
        state: touch
      register: var
    - debug:
        msg: "{{ var }}" 
    - lineinfile:
        path: /tmp/variables3
        line: "UID of newly created file is {{ var.uid }} and gid is {{ var.gid }}"










