---
- name: practice of variable precedence
  hosts: node1
  become: yes
  gather_facts: no
  vars:
    myvar: "This is a playbook variable"
  vars_files:
    - ~/automation/playbooks/practice_variables_file.yml
  tasks:
    - name: junst a debug message to output variables.
      debug:
        msg: "{{ myvar }}"
