---
- name: Changing SELINUX mode in Config file using Variables
  hosts: vmservers
  become: true
  vars:
    status: permissive
  tasks:
    - name: Changing SELINUX mode in /etc/selinux/config file
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX={{ status  }}'
...
