---
- name: icmp and port forwarding
  hosts: node1
  become: true
  tasks:
    - firewalld:
        zone: drop
        icmp_block_inversion: true
        immediate: yes
        permanent: yes
        state: enabled
    - firewalld:
        zone: drop
        icmp_block: echo-request
        state: enabled
        permanent: yes
        immediate: yes

    - name: redirect port 443 to 8443 with rich rule
      firewalld:
        rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
        zone: public
        state: enabled
        permanent: yes
        immediate: yes


