---
- name: process mnagement using ansible playbook
  hosts: node1
  become: yes
  tasks:
    - name: get running proceses list from remote host
      ignore_errors: yes
      shell: "ps -few | grep httpd | awk '{print $2}'"
      register: running_processes
    - name: printing process ids of httpd processes
      debug:
        msg: "{{ running_processes }}"
    - name: kill the running httpd processes
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"
...

