---
- name: file permissions with sticky bit
  hosts: node1
  become: yes
  tasks:
    - name: create file
      file:
        path: /tmp/nehrastaff2
        state: directory
        owner: root
        group: root
        mode: 1777
      register: ver
    - name: print
      debug:
        msg: "{{ ver }}"
...

