---
- name: create fs and mount it
  hosts: node1
  tasks:
    - name: create ext4 filesystem on logical volume
      filesystem:
        dev: /dev/vg.ansible/lv.ansible
        fstype: ext4
    - name: mounting it
      mount:
        path: /mnt/test_mount
        src: /dev/vg.ansible/lv.ansible
        fstype: ext4
        state: absent
        backup: yes
