---
- name: file permissions.
  hosts: node1
  become: true
  tasks:
    - name: Change access time of a file
      file:
        path: /etc/linux.conf
        state: file
        access_time: '202201021015.30'
