---
- name: Simple loops with yum command
  hosts: web
  tasks:
    - name: Install 5 packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - vsftpd
        - wget
        - stress
